### ISSUE TITLE
Add Travis CI for the project

### ISSUE THREAD

**Issue by ShekharReddy4** [KMITFOSS/openmrs-webgl-globe#11]
Add Travis CI for the project

**Comment by nysthee** [comment]
I can add a basic config but atm there are no tests? What would you like to do during ci runs?

**Comment by ShekharReddy4** [comment]
@nysthee please add the basic config I will add the test cases later... if there is anything that could  improve the project --you are welcome

**Comment by nysthee** [comment]
Can you add the project to Travis please? This is sth the project owner must do.
https://travis-ci.org/KMITFOSS/openmrs-webgl-globe 
Thx!

**Comment by ShekharReddy4** [comment]
@nysthee  I have added to Travis :)
